### ISSUE TITLE
Provide the Dockerfile for tcpcopy and intercept.

### ISSUE THREAD

**Issue by cobolbaby** [peiwal11/tcpcopy_implement#3]

**Comment by peiwal11** [comment]
Thanks for your response!
I include it in my new version.

**Comment by cobolbaby** [comment]
Please split the python service and the tcpcopy service into two separate containers.

**Comment by peiwal11** [comment]
Got it! I split it up.

**Comment by cobolbaby** [comment]
Here are a few tips for optimizing your deployment configuration:

1. The `entrypoint.sh` in `tcpcopy` contains hard-coded network addresses, making the `tcpcopy` image unsuitable for general use as a toolbox image.
2. Both the online server and the target server need to deploy the same python service. Based on the principle of reusability, it's recommended to extract the python service-related code and configurations into a separate directory.
3. The docker-compose file should have a file extension. Otherwise, IDEs cannot provide syntax highlighting, and it might be mistaken for an executable file.

**Comment by peiwal11** [comment]
thanks for your advice!
I have addressed those problems.
