### ISSUE TITLE
The simulated test cases should include the operation process (including route configuration).

### ISSUE THREAD

**Issue by cobolbaby** [peiwal11/tcpcopy_implement#5]

**Comment by peiwal11** [comment]
Please review the new version of the code and the README.md file to see if it clarifies any confusion. If you need further assistance or have additional questions, please don't hesitate to let me know!

**Comment by cobolbaby** [comment]
Describing the testing process is equivalent to writing test cases. You need to clearly describe which commands or actions the user needs to perform to achieve traffic copying.

**Comment by peiwal11** [comment]
I added Topic 6 in the README.md to illustrate how this project works, including detailed steps to achieve traffic copying. Let me know if it fully meets your requirements or if further details are needed.
